#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in metadata.json
#metadata

# use dependencies defined in Modulefile
# modulefile

# A module from the Puppet Forge
mod 'puppetlabs/stdlib'
mod 'puppetlabs/vcsrepo'
mod "puppetlabs/concat" "2.x"
mod "puppetlabs/ntp"
mod "zack/r10k"
mod "saz/ssh"
mod "saz/motd"

# A module from git
# mod 'puppetlabs-ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'
# mod 'UNILU-easybuild',
# 	:git => 'git://github.com/sylmarien/puppet-easybuild.git',
# 	:ref => 'v0.2.2'
# mod 'UNILU-softwareautoinstall',
#   :git => 'https://github.com/sylmarien/puppet-softwareAutoInstall.git',
#   :ref => 'devel'

# A module from a git branch/tag
# mod 'puppetlabs-apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => '1.4.x'

# A module from Github pre-packaged tarball
# mod 'puppetlabs-apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'
